# k8s/secrets/secret-dev.yaml
apiVersion: v1
kind: Secret
metadata:
  name: date-webapp-secrets-development
  namespace: test-webapp
type: Opaque
stringData:  # Usa stringData per evitare encoding base64 manuale
  DATABASE_PASSWORD: "dev_password"
  JWT_SECRET: "dev_jwt_secret_key"
  API_KEY: "dev_api_key"
