# k8s/secrets/secret-dev.yaml
apiVersion: v1
kind: Secret
metadata:
  name: date-webapp-secrets
  namespace: development
type: Opaque
stringData:  # Usa stringData per evitare encoding base64 manuale
  DATABASE_PASSWORD: "staging_password"
  JWT_SECRET: "staging_jwt_secret_key"
  API_KEY: "staging_api_key"
