# k8s/secrets/secret-dev.yaml
apiVersion: v1
kind: Secret
metadata:
  name: date-webapp-secrets-production
  namespace: test-webapp
type: Opaque
stringData:  # Usa stringData per evitare encoding base64 manuale
  DATABASE_PASSWORD: "prod_password"
  JWT_SECRET: "prod_jwt_secret_key"
  API_KEY: "prod_api_key"
