apiVersion: v1
kind: Secret
metadata:
  name: date-webapp-secrets
  labels:
    app: date-webapp
    environment: {{ .Values.config.APP_ENVIRONMENT }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.DATABASE_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  API_KEY: {{ .Values.secrets.API_KEY | quote }}
