apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.APP_NAME }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.APP_NAME }}
    environment: {{ .Values.config.APP_ENVIRONMENT }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: "service"
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"

spec:
  type: ClusterIP
  selector:
    app: {{ .Values.APP_NAME }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
